/* Generated By:JavaCC: Do not edit this line. adacConstants.java */
package traductor;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface adacConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int ALNUM = 6;
  /** RegularExpression Id. */
  int tCOM = 7;
  /** RegularExpression Id. */
  int tBEGIN = 8;
  /** RegularExpression Id. */
  int tBOOL = 9;
  /** RegularExpression Id. */
  int tCHAR = 10;
  /** RegularExpression Id. */
  int tINT = 11;
  /** RegularExpression Id. */
  int tEOL = 12;
  /** RegularExpression Id. */
  int tIDERR = 13;
  /** RegularExpression Id. */
  int tID = 14;
  /** RegularExpression Id. */
  int tERROR = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<LETTER>",
    "<DIGIT>",
    "<ALNUM>",
    "<tCOM>",
    "\"begin\"",
    "\"boolean\"",
    "\"character\"",
    "\"integer\"",
    "\";\"",
    "<tIDERR>",
    "<tID>",
    "<tERROR>",
  };

}
