/* Generated By:JavaCC: Do not edit this line. ejemploConstants.java */
package traductor;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ejemploConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tDIGITO = 1;
  /** RegularExpression Id. */
  int tNUM = 2;
  /** RegularExpression Id. */
  int tPAL_INT = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<tDIGITO>",
    "<tNUM>",
    "<tPAL_INT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
